article_index:
    path:     /
    defaults: { _controller: "RuralisBundle:Article:index" }
    methods:  GET

article_show:
    path:     /{id}/show
    defaults: { _controller: "RuralisBundle:Article:show" }
    methods:  GET

article_new:
    path:     /new
    defaults: { _controller: "RuralisBundle:Article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "RuralisBundle:Article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "RuralisBundle:Article:delete" }
    methods:  DELETE
